FROM andgr1it/relikpod-base:latest

WORKDIR /home/relik-user/relik

# Install Jupyter Notebook
RUN pip install jupyter

# Expose the Jupyter Notebook port
EXPOSE 8888

# Start Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
