FROM nvidia/cuda:12.0.0-base-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN adduser --disabled-password --gecos '' relik-user \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    curl wget git python3.11 python3-distutils python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s $(which python3) /usr/local/bin/python

USER relik-user
ENV PATH=${PATH}:/home/relik-user/.local/bin

# Set the working directory
COPY --chown=relik-user:relik-user . /home/relik-user/relik

RUN mkdir -p /home/relik-user/.cache/huggingface

# COREFEREE
WORKDIR /home/relik-user
RUN git clone https://github.com/richardpaulhudson/coreferee
WORKDIR /home/relik-user/coreferee

RUN sed -i '39s/spacy>=3.0.0,<3.6.0/spacy>=3.0.0,<3.8.0/' setup.cfg && \
    sed -i 's/to_version:             3.3.0/to_version:             3.8.0/g' coreferee/lang/en/config.cfg

RUN cat setup.cfg | grep spacy

RUN pip install --upgrade pip
RUN pip install .

# Install base dependencies
RUN pip install llama-index-extractors-relik llama-index-graph-stores-neo4j llama-index-llms-openai llama-index

# Download spacy model and install coreferee
RUN python -m spacy download en_core_web_lg && \
    python -m coreferee install en

WORKDIR /home/relik-user/relik